feat: update SapMachine version to 21.0.8 in Containerfile (#13)
* feat: update SapMachine version to 21.0.8 in Containerfile

This should fix this issue that came up because debian Trixie upgraded the default JRE:

java.lang.UnsupportedClassVersionError: HelloWorld has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 64.0

* fix java version